from typing import Optional,List
from enum import Enum
from pydantic import BaseModel

class details(str,Enum):
    buy="buy"
    sell="sell"

class Trade(BaseModel):
    asset_class: Optional[str]=...
    counterparty: Optional[str]=...
    instrument_id: str=...
    instrument_name: str=...
    trade_date_time: int=...
    trade_id:int=...
    trader: str=...
    price: int=...
    quantity: int=...
    buysell:str
